[package]
name = "forked"
version = "0.1.0"
authors = ["Sam MacLennan <sammaclennan2001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
